title: Today I learned...
author:
  name: Trevor K. Karn
  email: karnx018@umn.edu
  website: https://trevorkarn.github.io/
description: > # this means to ignore newlines until "show_excerpts:"
  This is a blog about math. I want to learn one new thing every day,
  and then write about it!

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github_username:  trevorkarn 

# Build settings
theme: minima

#plugins:
# - jekyll-feed
# - jekyll-seo-tag
